Connection:
  Username: MY_USERNAME
  Password: MY_PASSWORD
Criteria:
  ProjectId: 124344740866
  WorkflowId: 715544700540
Workflow:
  Defined: Defined
  In-Progress: In-Progress
  Completed: Completed
  Accepted: Accepted
